const express = require("express");
const app = express();
const db = require("./db.js");
const multer = require("multer");
const uidSafe = require("uid-safe");
const path = require("path");
const s3 = require("./s3.js"); //added

app.use(express.static("./public"));

app.use(express.json()); //this middleware helps us parse json format request bodies;

const diskStorage = multer.diskStorage({
    // Multer is a node.js middleware for handling multipart/form-data , which is primarily used for uploading files.
    destination: function (req, file, callback) {
        callback(null, __dirname + "/uploads");
    },
    filename: function (req, file, callback) {
        uidSafe(24).then(function (uid) {
            callback(null, uid + path.extname(file.originalname));
        });
    },
    // The destination function tells multer to put files in the uploads directory and the filename function tells multer to use as the file name the unique id generated by the call to uidSafe with the extension of the original file name appended to it.
});

const uploader = multer({
    storage: diskStorage,
    limits: {
        fileSize: 2097152,
    },
});

//The object returned from this call to multer has middleware functions attached to it that can be used to handle uploads on specific routes

app.post(
    "/upload.json",
    uploader.single("file"),
    //The call to single indicates that we are only expecting one file.
    s3.upload,
    function (req, res) {
        console.log("req.body-------------", req.body);
        console.log("Post/ upload");
        const amazonUrl = "https://s3.amazonaws.com/spicedling/";
        //INSERT into images
        const { title, description, username } = req.body;
        const { filename } = req.file;
        const url = `${amazonUrl}${filename}`;
        db.uploadImages(url, username, title, description)
            .then((val) => {
                //response back to the clientide to your Vue (app.js). Object that represents the img.
                res.json(val.rows[0]);
            })
            .catch((err) => {
                console.log("Error in the post /upload  db.uploadImages", err);
            });
    }
);
//------------------------Modal

app.get("/modal/:modalImage", (req, res) => {
    console.log("We are in the modal");
    db.selectModalImage(req.params.modalImage)
        .then((val) => {
            res.json(val.rows[0]);
        })
        .catch((err) => {
            console.log("Error in the / /modal/:modalImage", err);
        });
});

//------------------------------------

app.get("/images.json", (req, res) => {
    console.log("We are here");
    db.selectImages()
        .then((images) => {
            res.json(images.rows);
        })
        .catch((err) => {
            console.log("Error in the /", err);
        });
});

///must stay at the end
app.get("*", (req, res) => {
    res.sendFile(`${__dirname}/index.html`);
});
app.listen(8080, () => console.log(`I'm listening.`));
